### ISSUE TITLE
SEO: GA4 support

### ISSUE THREAD

**Issue by Reggie-Gonzalez** [on-associates/OTA-Insight#2]
Ga4 support, OTAI need support finishing Dustin's[ brief](https://docs.google.com/document/d/1FaldE9aFBAWjsWXVGB9BLyTS8CUVBu3CA4WLbU5Mndw/edit#heading=h.7fnexqq2rdbw), incomplete and malfunctioning. Also need an audit to identify triggers that can be reused for the new site. requests that everything is served in the documentation for MOPS team to reference. List of GA4 issues [here](https://docs.google.com/document/d/1du2wiQzAK9NdYZ-QBwBukjjBhjrbVUAi6L0nfAOZMqg/edit). A possible issue is that the client is utilizing a custom plug-in that they would like us to replicate. Ollie may need additional support from the devs. 

Ollie has shared the audit, and the client has requested that we only action the dashboard for the new site only. Staging should be stable enough for this next week on 25/9. Currently the only action is the client meeting for alignment tomorrow 21/9. 

Update 26/9: The client has added additional context on the page & form categories in the statement of work [here](https://docs.google.com/document/d/1FaldE9aFBAWjsWXVGB9BLyTS8CUVBu3CA4WLbU5Mndw/edit#heading=h.8e36fzfuyq0b)

Update 18/10: We are sharing updated dashboard with documentation with client today. The custom plug-in is still under investigation and being picked up with Michael G. Plan is to share progress today, giving the client team time to share questions with Ollie Boyd on his last day before holiday. Final implementation will be on 30/10. Two hours allocated to include testing. 

```[tasklist]
### Tasks
- [x] Ga4 audit
- [x] Client meeting for alignment on requirements 21/9 (1 hour)
- [x] Updated dashboard & documentation (3 days)
- [ ] Start implementation of dashboard on new site w/c 6/11 (2 hours)
```

**Comment by Reggie-Gonzalez** [comment]
@OllieBoydON Lets have a chat once you'd had a chance to review the brief and list of issues? Im curious if 1) this is worth fixing on the old site 2) if we still believe we can do this under a 4 day estimation

**Comment by Reggie-Gonzalez** [comment]
Audit of current GA4 dashboard. ON will provide 1) Outline of critical issues that we recommend are fixed on the current site, at your approval we will action and 2) A recommendation of a setup for the new site, our aim will be to repurpose as much of the plan from the current site, at your approval we will action. We will also provide documentation of the final dashboard for the MOPS team to use as a reference. See item 10 below for exclusion.

**Timeline**

- [ ] Audit of GA4 w/c 4/9 ; Client to decide if we action fixes based on our effort estimation

- [ ] Implementation of new dashboard will be implemented during sprint 8 w/c 18/9

**Comment by lizzie-madebyon** [comment]
@Reggie-Gonzalez Update from SEO call - this work should be all completed but let me and @OllieBoydON know if anything is remaining. Thanks!

**Comment by lizzie-madebyon** [comment]
**Update from Reggie:** 
The client on OTAI will share an update with me this morning. They spent last week reviewing the audit and must decide if they would like to proceed with either a GA4 dashboard on the current site or only for the new one.
Their answer will determine if Ollie has work this week, if it’s only the latter then I may only need an hour this week to review requirements, but the actual task won’t be scheduled until next week.

**Comment by Reggie-Gonzalez** [comment]
hi @lizzie-madebyon updated this ticket, the start date of GA4 is on 3/10 -- expected finish date of 6/10

**Comment by lizzie-madebyon** [comment]
Update: the client is expecting a dashboard to be delivered as part of the scope. Non-negotiable. All details are included in the overview above but @Reggie-Gonzalez can jump on a call next week if there are any questions

**Comment by OllieBoydON** [comment]
Just to confirm, this task will be softly split into two

1. Realigning the current GTM set up to work with the new website
2. Looking at how to replicate the AI custom tag used to split the marketing UTMs into cookies.

**Comment by lizzie-madebyon** [comment]
cc @Reggie-Gonzalez

**Comment by Reggie-Gonzalez** [comment]
@OllieBoydON Can you add the latest update here for the custom plug-in. Is this something Michael Gunner can address on his own while you're on holiday or shall we prep client that it is best to reserve post-launch? cc: @leonmadebyon

**Comment by OllieBoydON** [comment]
Latest documentation provided here - https://docs.google.com/spreadsheets/d/1IGnhU4E6CrjrtRSiEj4qI06_bTOazz3S9T_oBf0vQdw/edit#gid=557429239 

OTA have provided comments, will answer by the 7th November

**Comment by OllieBoydON** [comment]
Spoke with the client, we received some updates from them. 

- Select_content Event Parameters
  - Content_heading - Fine to drop as it's not something they have really used
  - Content_location - They are happy to drop this too but I believe it's been updated
- Items double firing
  - Appears items are double firing due to the default event names. 
  - OTA recommended the custom page_view tag, we should look to pause this and move the event parameters within into the ga_config tag
  - Forms are also double firing, OTA would rather not move away from the default event name and would instead like to pause the GA4 default. We will investgate other naming conventions or to potentially pause the default form_submit event in GA4

**Comment by OllieBoydON** [comment]
Action Plan based on the above 

- Pausing content_heading - 10 minutes
- Updating the content_location code with the new code from Kevin + QA - 1 hour
- Moving page_view parameters to the ga_config event + QA - 2 hours
- Forms - Either change event name + QA or turn off default event tracking in GA4 + QA - 1 hour either way

Regarding the double firing of forms
1. GA4 - form_submit is a default event that tracks any form completions
2. GTM - We have a custom tag that sends the Mofu / Bofu information when a form is completed (so this also sends a form_submit event)

So I would recommend we update the name of the even within the GTM tag. This should be changed from form_submit to something else, like form_complete or something similar. There doesn't appear any way via REGEX to help with their reporting however, so their reporting will need to be modified to allow the new form event. 

If OTA would still prefer to keep the form_submit event and turn off the GA4, then we can work that way, but it must be a decision by them.

**Comment by lizzie-madebyon** [comment]
Waiting for separate budget for GA work - est time 4.5/5 hours

**Comment by OllieBoydON** [comment]
Work all complete but need to flag a big issue. 

1. Pausing content_heading - Complete
2. Updating the content_location code with the new code from Kevin + QA - Complete
3. Moving page_view parameters to the ga_config event + QA - Complete
4. Forms - Either change event name + QA or turn off default event tracking in GA4 + QA - Done but issues

Firstly, the content_heading was paused, and the new content_location is in place. We also managed to add the parameters to the ga_config file and see the information is firing correctly into GA4. 

The forms I have also modified but I have had to make them fire Once Per Page and changed the name of the event to avoid data duplication. This has highlighted an issue with the website where it appears to be using URL fragments, which means you're technically only on 1 page, despite how many pages you can navigate to. 

This has a huge impact on the above, as if you complete 1 form, and then a 2nd forms within a single session. The 2nd form will not be counted as GTM believes we are still on the same page. 

Documentation all updated - https://docs.google.com/spreadsheets/d/1IGnhU4E6CrjrtRSiEj4qI06_bTOazz3S9T_oBf0vQdw/edit#gid=1822371912

**Comment by lizzie-madebyon** [comment]
Closing as info in other OTA ticket
